apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-service
  namespace: efk
  labels:
    app: simple-webapp
spec:
  selector:
    app: simple-webapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 5005
    nodePort: 30001 # NodePort range is 30000-32767